version: '3.5'

services:
  postgres:
    container_name: pg_container
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - vpostgres:/data/postgres
    tty: true
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ua
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - vpgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api:
    container_name: api_container
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  migration:
    build: 
      context: .
    command: 
      [
        "./wait-for-it/wait-for-it.sh",
        "postgres:5432",
        "--",
        "npm",
        "run",
        "migration:update"
      ]
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  vpostgres: null
  vpgadmin: